reddit/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resources :posts, except: [:index]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]
end

reddit/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true

  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User
    
  has_many :post_subs,
    inverse_of: :post
    
  has_many :subs, 
    through: :post_subs, 
    source: :sub
  
end

reddit/app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :bigint(8)        not null, primary key
#  post_id    :integer          not null
#  sub_id     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ApplicationRecord
  belongs_to :post
  belongs_to :sub
end

reddit/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint(8)        not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, presence: true
  
  belongs_to :moderator,
    foreign_key: :moderator_id,
    class_name: :User
    
  has_many :post_subs, 
    inverse_of: :sub
  
  has_many :subs,
    through: :post_subs,
    source: :sub
    

end

reddit/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }
  
  attr_reader :password
  
  before_validation :ensure_session_token

  has_many :moderated_subs,
    foreign_key: :moderator_id,
    class_name: :Sub
    
  has_many :posts,
    foreign_key: :author_id,
    class_name: :Post
    
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
  
  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end
  
  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    if user && user.is_password?(password)
      return user
    end
    nil
    
  end
end

reddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def log_in(user)
    session[:session_token] = user.reset_session_token
  end
  
  helper_method :current_user
  
  def log_out!
    current_user.reset_session_token
    session[:session_token] = nil
    @current_user = nil
  end
  
  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end
  
  def require_login
    redirect_to new_session_url unless current_user
  end
  
end

reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  private
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

reddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    
    if @user
      log_in(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["Invalid Credentials Dummy!"]
      render :new
    end
  end
  
  def destroy
    log_out!
    
    redirect_to new_session_url
  end
end

reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  
  before_action :require_login
  
  def new
    @sub = Sub.new
  end
  
  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end
  
  def show
    @sub = Sub.find(params[:id])
  end
  
  def index
    @subs = Sub.all
  end
  
  def edit
  
    @sub = Sub.find(params[:id])
    unless current_user.id == @sub.moderator_id
      redirect_to subs_url
      return
    end
    
    
  
  end
  
  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end
  
  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

reddit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      log_in(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  
  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

reddit/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit/app/helpers/posts_helper.rb
module PostsHelper
end

reddit/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit/app/helpers/subs_helper.rb
module SubsHelper
end

reddit/app/helpers/users_helper.rb
module UsersHelper
end

reddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div class="header">
      <header>
        <nav>
          <h1>Ruddit</h1>
          <ul>
            <li>
              <% if current_user %>
                <form action="<%= session_url %>" method="post">
                  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                  <input type="hidden" name="_method" value="delete">
                  <input type="submit" name="" value="Sign Out">
                </form>
              <% end %>
            </li>
            
            <li>
            <form class="" action="<%= subs_url %>" method="post">
              <input type="hidden" name="_method" value="get">
              <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
              <label>
                <input type="submit" class="button" value="All Subs">
              </label>
            </form>
          </li>
          </ul>
        </nav>
      </header>
    </div>
    
    <div class="content">
      <%= yield %>
    </div>
    
    
    
  </body>
</html>

reddit/app/views/posts/new.html.erb
<div class="form-container">
  <div class="form-content">
    <h1>Create New Post dude...cool...hey! great job...dude</h1>
    
    <div class="errors">
      <% if flash.now[:errors] %>
        <% flash.now[:errors].each do |error| %>
          <%= error %>
        <% end %>
      <% end %>
    </div>
    
    <form action="<%= posts_url %>" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      
      <label>
      Title
      <input type="text" name="post[title]" placeholder="required">
      </label>
      
      <label>
      URL
      
      <input type="text" name="post[url]" placeholder="optional">
      </label>
      
      <label>
      Content
      
      <input type="text" name="post[content]" placeholder="optional">
      </label>
      
      <label>
      Subs
      
      <% Sub.all.each do |sub| %>
        <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>">
        <%= sub.title %>
        
      <% end %>
      </label>
      
      <input type="submit" value="Create New Post" class="button">
      
    </form>
  </div>
  
</div>

reddit/app/views/posts/show.html.erb
<div class="content_display">
  <div class="title">
    <%= @post.title %>
  </div>
  <div class="url">
    <%= @post.url %>
  </div>
  <div class="author">
    Posted by this very swell person:     
    <%= @post.author.username %>
  </div>
  <div class="subs">
    Subs: 
    <% @post.subs.each do |sub| %>
      <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
    <% end %>
  </div>
  
</div>

reddit/app/views/subs/edit.html.erb
<div class="form-container">
  <div class="form-content">
    <h1>Edit Sub</h1>
    
    <div class="errors">
      <% if flash.now[:errors] %>
        <% flash.now[:errors].each do |error| %>
          <%= error %>
        <% end %>
      <% end %>
    </div>
    
    <form action="<%= sub_url(@sub) %>" method="post">
      <input type="hidden" name="_method" value="patch">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <label>
      Title
      <input type="text" name="sub[title]" value="<%= @sub.title %>">
      </label>
      <label>
      Description
      <input type="text" name="sub[description]" value="<%= @sub.description %>">
      </label>
      <input type="submit" value="Edit Sub" class="button">
      
    </form>
  </div>
  
</div>

reddit/app/views/subs/index.html.erb
<div class="content_display">
  <h1>Welcome to All Subs</h1>

  <div class="sub-list">
    <% @subs.each do |sub| %>
      <div class="sub-list-item">
        <i class="fas fa-chess-queen"></i> <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
      </div>
    <% end %>
  </div>

  <form class="" action="<%= new_sub_url %>" method="post">
    <input type="hidden" name="_method" value="get">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label>
      <input type="submit" class="button" value="New Sub">
    </label>
  </form>  
</div>

reddit/app/views/subs/new.html.erb
<div class="form-container">
  <div class="form-content">
    <h1>Create New Sub</h1>
    
    <div class="errors">
      <% if flash.now[:errors] %>
        <% flash.now[:errors].each do |error| %>
          <%= error %>
        <% end %>
      <% end %>
    </div>
    
    <form action="<%= subs_url %>" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <label>
      Title

      <input type="text" name="sub[title]" value="">
      </label>

      <label>
      Description

      <input type="text" name="sub[description]" value="">
      </label>

      <input type="submit" value="Create New Sub" class="button">
      
    </form>
  </div>
  
</div>

reddit/app/views/subs/show.html.erb
<div class="content_display">
  <div class="title">
    <%= @sub.title %>
  </div>
  <div class="description">
    <%= @sub.description %>
  </div>
  <div class="moderator">
    Moderated By:     
    <%= @sub.moderator.username %>
  </div>
  <form class="" action="<%= subs_url %>" method="post">
    <input type="hidden" name="_method" value="get">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label>
      <input type="submit" class="button" value="All Subs">
    </label>
  </form>
</div>

reddit/app/views/users/new.html.erb
<div class="form-container">
  <div class="form-content">
    
    <div class="errors">
      <% if flash.now[:errors] %>
        <% flash.now[:errors].each do |error| %>
          <%= error %>
        <% end %>
      <% end %>
    </div>
    
    <h1>Sign Up</h1>
    <form action="<%= users_url %>" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <label>
      Username
      
      <input type="text" name="user[username]" value="">
      </label>
      
      
      <label>
      Password
      
      <input type="password" name="user[password]" value="">
      </label>
      
      <input type="submit" value="Sign Up" class="button">
      
    </form>
  </div>
  
</div>